# reload
map ctrl+alt+f5 load_config_file

# default shell
shell /usr/bin/zsh

# WINDOWS
# ===========================================

# default window split
map ctrl+alt+enter launch --cwd=current

# close selected window
map ctrl+alt+w close_window

# ask when closing the window 
confirm_os_window_close 1

# grid mode
enabled_layouts grid, stack

# switching between windows
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

# fullscreen 
map ctrl+alt+z toggle_layout stack

# TABS
# =============================================

# new tab (curent location)
map ctrl+alt+t new_tab_with_cwd

# close tab
map ctrl+alt+d close_tab

# switching between tabs 
map ctrl+tab next_tab

# tabs bar style
tab_bar_style powerline

# change the tab name
map ctrl+alt+i set_tab_title

# FONT
# ==============================================

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
disable_ligatures never

# URL
# ==============================================

# Underline when the cursor hovers over it
url_style straight

# use default browser
open_url_with default

# url color
url_color #0087bd

# number all the links on the screen
map ctrl+alt+e open_url_with_hints

# Turn the mouse cursor to a "hand" shape when you hover over the URL. 
default_pointer_shape arrow
pointer_shape_when_grabbed hand

# MOUSE
# ==============================================

# auto copy to selected text
copy_on_select yes

# scrollback
scrollback_lines 10000

# hide mouse cursor when typing
mouse_hide_wait 2.0

# paste with scroll click
map middle_release paste_from_selection
